import { useEffect, useRef, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { FaExternalLinkAlt, FaGithub } from "react-icons/fa";
import { fallbackProjects } from "../data";
import type { Project } from "../types";
import { SectionHeading } from "./shared";

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? (import.meta.env.DEV ? "http://localhost:8000" : "");
const highlights: Record<string, string[]> = { "lovelens-ai": ["React and TypeScript product interface", "AI integration for compatibility-focused product features"], "solar-website": ["Responsive React interface with scroll animations", "WhatsApp-based inquiry path and production deployment"], "student-attendance-system": ["JWT authentication and multiple REST API modules", "Vue 3 frontend with Spring Boot and MySQL"], "uk-payroll-calculator": ["Weekly pay workflows for deductions, overtime, and expenses", "Next.js and NestJS application architecture with Prisma"] };

function useProjects() { const [projects, setProjects] = useState<Project[]>(fallbackProjects); useEffect(() => { const controller = new AbortController(); fetch(`${API_BASE_URL}/api/projects`, { signal: controller.signal }).then((response) => response.ok ? response.json() : Promise.reject()).then((data: Project[]) => Array.isArray(data) && setProjects(data)).catch(() => undefined); return () => controller.abort(); }, []); return projects; }
export function projectStory(description: string) { const values = description.replace("Problem: ", "").replace("Solution: ", "|").replace("Result: ", "|").split("|").map((item) => item.trim()); return { problem: values[0] ?? description, solution: values[1] ?? "", outcome: values[2] ?? "" }; }

export function Projects() { const projects = useProjects(); const reducedMotion = useReducedMotion(); const gridRef = useRef<HTMLDivElement>(null); const [eligible, setEligible] = useState(false); useEffect(() => { if (reducedMotion || !gridRef.current || typeof IntersectionObserver === "undefined" || typeof window.matchMedia !== "function" || !window.matchMedia("(min-width: 1024px)").matches) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setEligible(true); observer.disconnect(); } }, { rootMargin: "320px 0px" }); observer.observe(gridRef.current); return () => observer.disconnect(); }, [reducedMotion]); useEffect(() => { if (!eligible || !gridRef.current) return; let active = true; let context: { revert: () => void } | undefined; void Promise.all([import("gsap"), import("gsap/ScrollTrigger")]).then(([core, plugin]) => { if (!active || !gridRef.current) return; const gsap = core.gsap; gsap.registerPlugin(plugin.ScrollTrigger); context = gsap.context(() => { const cards = gsap.utils.toArray<HTMLElement>(".project-card", gridRef.current); if (cards.length < 2) return; const timeline = gsap.timeline({ scrollTrigger: { trigger: gridRef.current, start: "top 18%", end: `+=${cards.length * 420}`, pin: true, scrub: .7, anticipatePin: 1 } }); cards.slice(1).forEach((card, index) => { timeline.to(cards[index], { opacity: .32, scale: .96, y: -10, duration: 1 }, index).to(card, { opacity: 1, scale: 1, y: 0, duration: 1 }, index); }); }, gridRef); }).catch(() => undefined); return () => { active = false; context?.revert(); }; }, [eligible, projects.length]); return <section id="projects" className="section projects-section"><div className="container"><SectionHeading eyebrow="02 / Projects" title="Engineering work, explained clearly.">Selected applications with the context, implementation, and proof behind each build.</SectionHeading><div ref={gridRef} className="projects-grid grid gap-5 md:grid-cols-2">{projects.filter((project) => project.featured).map((project, index) => <ProjectCard project={project} index={index} key={project.id} />)}</div></div></section>; }

function ProjectCard({ project, index }: { project: Project; index: number }) { const reducedMotion = useReducedMotion(); const caseStudy = projectStory(project.description); const isSolar = project.id === "solar-website"; return <motion.article className={`project-card glass-card ${isSolar ? "project-card-featured" : ""}`} initial={reducedMotion ? false : { opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.15 }} transition={{ delay: index * 0.07, duration: 0.35 }}><span className="project-number">0{index + 1}</span>{isSolar && <div className="work-labels"><span>Client Work</span><span>Production</span></div>}<h3>{project.title}</h3><div className="project-case"><section><h4>Problem</h4><p>{caseStudy.problem}</p></section><section><h4>Solution</h4><p>{caseStudy.solution}</p></section><section><h4>Implementation / outcome</h4><p>{caseStudy.outcome}</p></section></div><section className="project-highlights"><h4>Engineering highlights</h4><ul>{(highlights[project.id] ?? ["Implemented a focused application workflow using the listed technology stack."]).map((highlight) => <li key={highlight}>{highlight}</li>)}</ul></section><div className="mt-6 flex flex-wrap gap-2">{project.tech.map((tech) => <span className="tech-badge" key={tech}>{tech}</span>)}</div><div className="mt-8 flex flex-wrap gap-4"><a className="text-link" href={project.githubUrl} target="_blank" rel="noopener noreferrer">GitHub <FaGithub /></a>{project.liveUrl && <a className="text-link" href={project.liveUrl} target="_blank" rel="noopener noreferrer">Live demo <FaExternalLinkAlt /></a>}</div></motion.article>; }
